---
title: "Decision Tree and RandomForest"
author: "Dipesh Poudel"
date: "12/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
```

```{r}
data<-read_csv('Cardiotocographic.csv')
```
```{r}
str(data)
```
```{r}
library(dplyr)
```

```{r}
table(data$NSP)
```
```{r}

ndata<-select(data,c(LB,AC,FM,NSP))
```

```{r}
data$NSPF<-factor(data$NSP)
```

```{r}
str(data)
```
```{r}
set.seed(1234)
ind<-sample(2,nrow(data), replace = T,prob = c(0.8,0.2))
train<-data[ind==1,]
test<-data[ind==2,]
```

```{r}
library(party)
```
```{r}
tree<-ctree(NSPF~LB+AC+FM,data = train)
```

```{r}
tree
```

```{r}
plot(tree)
```

```{r}
tree1<-ctree(NSPF~LB+AC+FM,data = train,controls = ctree_control(mincriterion = 0.99,minsplit = 500))
```

```{r}
head(predict(tree,type="prob"))
```

```{r}
predict(tree,test)
```
```{r}
(tab<-table(predict(tree),train$NSPF))
```

```{r}
accuracy<-sum(diag(tab)/sum(tab))
mce<-1-accuracy
accuracy
mce
```

```{r}
pred.test<-predict(tree,newdata=test)
```

```{r}
(tab1<-table(pred.test,test$NSPF))
```
```{r}
accuracy1<-sum(diag(tab1)/sum(tab1))
mce1<-1-accuracy1
accuracy1
mce1
```

```{r}
data<-data[,-23]
```

```{r}
library(randomForest)
```
```{r}
set.seed(22)
data$NSP<-factor(data$NSP)
ind<-sample(2,nrow(data), replace = T,prob = c(0.8,0.2))
train<-data[ind==1,]
test<-data[ind==2,]
rfm<-randomForest(NSP~.,data=data)
```

```{r}
rfm
```
```{r}
library(caret)
```
```{r}
p2<-predict(rfm,test)
confusionMatrix(p2,test$NSP)
```

